---
title: "WillMP2Documentation"
author: "William Nelson"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# App Purpose:

Our app's primary function is as a tool in order to visualize and better understand the mtcars dataset through multiple different visual graphs.

# How it Works:

Our app presents an interactive user interface with the option to display 4 different visual graphs including scatter plot, box plot, bar graph, and correlation plot. The user is able to select two variables to display on the graph from 11 options. In addition, the user has several options to customize how the visuals are displayed such as plot color, adjusting the bar graph's width and scatter plot dot size, and whether or not to display the car names and regression line on the scatter plot. Lastly our user can decide whether or not to show the summary statistics of the two variables selected.

# Insights:

There are many interesting patterns that emerge when plotting the variables on different graphs. An example is the strong negative correlation between miles per gallon and weight that can be seen on both the scatter plot and the correlation plot which shows how heavier cars tend to have lower fuel efficiency. Another example that is showcased through both the scatter plot and the correlation plot is the strong negative correlation between horsepower and miles per gallon showing how as horsepower increases miles per gallon decreases. Lastly by plotting miles per gallon against am on the box plot which showcases how manual cars generally have better miles per gallon than automatic.

# Reflection:
